spring:
  application:
    name: Mes
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mes
    username: root
    password: 123456

server:
  port: 8091
  address: 0.0.0.0
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    type-handlers-package: com.baomidou.mybatisplus.extension.handlers
  mapper-locations: classpath:com/example/mes/mapper/*.xml
  type-aliases-package: com.example.mes.pojo
